### ISSUE TITLE
Error: Cannot find module 'autoprefixer' w/ with-tailwind starter

### ISSUE THREAD

**Issue by ktkennychow** [nandorojo/solito#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

Next.js will crash with `Error: Cannot find module 'autoprefixer'`

### Steps To Reproduce

1. Create w/ npx create-solito-app@latest my-solito-app -t with-tailwind
2. yarn web/bun web
3. Next.js crashes w/ `Error: Cannot find module 'autoprefixer'`

TEMP FIX: I got it running by simply installing "autoprefixer" as a dev dependency in /apps/next.
Not even sure if it is the right place or if it should be in root.

### Versions

```markdown
- Solito: 0.2.0
- Next.js: 14.2.6
- Expo:/
- React Native:/
```

_No response_

**Comment by madmonkey08** [comment]
The project will be abandoned? The error still happening

**Comment by nandorojo** [comment]
https://github.com/nandorojo/solito/pull/480#issuecomment-2315953840

Related to reverting this PR

**Comment by nandorojo** [comment]
@madmonkey08 you clicked “not urgent” in your issue, so there is no need to tag and follow up.

**Comment by ktkennychow** [comment]
@nandorojo thought I had choose either or, since I did not sponsor.
The versions of Expo dependency libraries seems to be out of sync too, it is easier fixable following Expo console warnings.
But yea, not working out of the box w/ known package manager/installer script problem introduced by #480.
Would love to help, let me know if the original writer is not available to debug.

**Comment by ktkennychow** [comment]
@Arturo-Lopez 
In root/package.json add `"autoprefixer": "^10.4.14"`
and install that dependency by `yarn install` again

**Comment by nandorojo** [comment]
@ktkennychow would you be open to sending a PR to add that to the example template? Would love to merge that and fix this for others! Thanks for sharing the fix

**Comment by ktkennychow** [comment]
@nandorojo Sure, I will fix the version of dependencies for Expo while I am at it.

**Comment by ktkennychow** [comment]
@nandorojo #491 PR created :)
